parameters:
  amazon_s3_key: ~
  amazon_s3_secret: ~
  amazon_s3_region: ~
  amazon_s3_bucket: ~


services:
    bongo.stream_wrapper:
      class: Bongo\S3AssetInstallerBundle\StreamWrapperAWSS3
      arguments: ['%amazon_s3_key%',"%amazon_s3_secret%","%amazon_s3_region%"]

    bongo.asset.aws_s3.client:
      class: Aws\S3\S3Client
      factory: [Aws\S3\S3Client, 'factory']
      arguments:
        - version: latest
          region: '%amazon_s3_region%'
          credentials:
            key: '%amazon_s3_key%'
            secret: '%amazon_s3_secret%'
