parameters:
  aws_s3_key: ~
  aws_s3_secret: ~
  aws_s3_region: ~
  aws_s3_bucket: ~


services:
    bongo.stream_wrapper:
      class: Bongo\S3AssetInstallerBundle\StreamWrapperAWSS3
      arguments: ['%amazon_s3.key%',"%amazon_s3.secret%","%amazon_s3.region%"]

    bongo.asset.aws_s3.client:
      class: Aws\S3\S3Client
      factory: [Aws\S3\S3Client, 'factory']
      arguments:
        - version: latest
          region: '%amazon_s3.region%'
          credentials:
            key: '%amazon_s3.key%'
            secret: '%amazon_s3.secret%'
