services:
    bongo.stream_wrapper:
      class: Bongo\S3AssetInstallerBundle\StreamWrapperAWSS3
      arguments: ['%bongo_s3_asset_installer.amazon_s3_key%',"%bongo_s3_asset_installer.amazon_s3_secret%","%bongo_s3_asset_installer.amazon_s3_region%"]

    bongo.s3client:
      class: Aws\S3\S3Client
      factory: [Aws\S3\S3Client, factory]
      arguments:
          - version: latest
            region: "%bongo_s3_asset_installer.amazon_s3_region%"
            credentials: { key: "%bongo_s3_asset_installer.amazon_s3_key%", secret: "%bongo_s3_asset_installer.amazon_s3_secret%" }
